"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const persona_1 = require("./persona");
const direccion_1 = require("./direccion");
const mail_1 = require("./mail");
const telefono_1 = require("./telefono");
const primeraResidenciaSheila = new direccion_1.Direccion("Carrer del Bages", 14, 7, "C", 08192, "Sant quirze del vallès", "Barcelona");
const segundaResidenciaSheila = new direccion_1.Direccion("Calle Desfiladero de los Arrudos", 4, false, false, 33212, "Gijón", "Asturias");
const mailSheila = new mail_1.Mail("personal", "correosheila@gmail.com");
const telefonoFijoSheila = new telefono_1.Telefono("fijo", 937498333);
const telefonoMovilSheila = new telefono_1.Telefono("movil", 663889238);
const datosSheila = new persona_1.Persona('Sheila', 'Lopez Murillo', 23, '47474747G', new Date(1999, 3, 4), 'lila', 'mujer', [primeraResidenciaSheila, segundaResidenciaSheila], [mailSheila], [telefonoFijoSheila, telefonoMovilSheila], "Trabaja en la localidad de la primera residencia");
const primeraResidenciaMarc = new direccion_1.Direccion("Carrer del Kurdistan", 3, 4, "b", 08805, "sabadell", "Barcelona");
const segundaResidenciaMarc = new direccion_1.Direccion("Carrer de Màrius Torres", 21, 2, "D", 08173, "Sant Cugat del Vallès", "Barcelona");
const mailPersonalMarc = new mail_1.Mail("personal", "correoejemplomarc@hotmail.com");
const mailTrabajoMarc = new mail_1.Mail("personal", "correotrabajomarc@gmail.com");
const telefonoFijoMarc = new telefono_1.Telefono("fijo", 984768934);
const telefonoMovilMarcPersonal = new telefono_1.Telefono("movil", 774893474);
const telefonoMovilMarcTrabajo = new telefono_1.Telefono("movil", 66002284);
const datosMarc = new persona_1.Persona('Marc', 'Hernandez Cortes', 21, '89892834E', new Date(1991, 5, 4), 'azul', 'hombre', [primeraResidenciaMarc, segundaResidenciaMarc], [mailPersonalMarc, mailTrabajoMarc], [telefonoFijoMarc, telefonoMovilMarcPersonal, telefonoMovilMarcTrabajo], "Tiene la segunda residencia alquilada todo el año");
const primeraResidenciaPilar = new direccion_1.Direccion("Calle de los Arenales", 1, 6, "C", 46530, "Puçol", "Valencia");
const segundaResidenciaPilar = new direccion_1.Direccion("Carrer de Misser Rufet", 8, 1, "A", 08720, "Vilafranca del Penedès", "Barcelona");
const mailPersonalPilar = new mail_1.Mail("personal", "correopersonalpilar@gmail.com");
const mailTrabajoPilar = new mail_1.Mail("trabajo", "correopilartrabajo@hotmail.es");
const telefonoFijoPilar = new telefono_1.Telefono("fijo", 987364788);
const telefonoMovilPilar = new telefono_1.Telefono("movil", 669830273);
const datosPilar = new persona_1.Persona('Pilar', 'Bermúdez Diaz', 53, '78374938Q', new Date(1967, 0, 9), 'rojo', 'mujer', [primeraResidenciaPilar, segundaResidenciaPilar], [mailPersonalPilar, mailTrabajoPilar], [telefonoFijoPilar, telefonoMovilPilar], "La segunda residencia es de alquiler");
console.log("Contactos antes del cambio:");
console.log(datosSheila);
console.log(datosMarc);
console.log(datosPilar);
const agenda = new Array(datosSheila, datosMarc, datosPilar);
const dniABuscar = "89892834E";
const personaAEditar = agenda.find(persona => persona.dni === dniABuscar);
const nuevaDireccion = new direccion_1.Direccion("Calle las eras", 35, 1, false, 44792, "Josa", "Teruel");
const nuevoMail = new mail_1.Mail("trabajo", "nuevocorreomarc@gmail.com");
const nuevoTelefono = new telefono_1.Telefono("fijo", 98765645);
personaAEditar.agregarNuevaDireccion(nuevaDireccion);
personaAEditar.agregarNuevoMail(nuevoMail);
personaAEditar.agregarNuevoTelefono(nuevoTelefono);
console.log("Contactos después del cambio:");
console.log(datosSheila);
console.log(datosMarc);
console.log(datosPilar);
//# sourceMappingURL=main.js.map